[
  {
    "userId": "ObjectId('507f1f77bcf86cd799439011')",
    "email": "alice@example.com",
    "firstName": "Alice",
    "lastName": "Smith",
    "fullName": "Alice Smith",
    "lastSeen": "2023-04-27T12:00:00Z",
    "aboutMe": "Dedicated AI researcher.",
    "connectionInterest": "Looking for AI enthusiasts.",
    "industryInterests": ["Artificial Intelligence", "Tech"],
    "interestedInBeingACofounder": false,
    "currentSchool": "Harvard",
    "programType": "Computer Science",
    "birthDate": "1992-06-15T00:00:00Z",
    "profilePicture": "https://example.com/path/to/photo.jpg",
    "previousEducation": "MIT",
    "employmentHistory": "Google, AI Developer",
    "hasIdea": "Have ideas but not committed",
    "technical": true,
    "impressiveAccomplishment": "Developed an AI that can read emotions."
  },
  {
    "userId": "ObjectId('507f1f77bcf86cd799439012')",
    "email": "bob@example.com",
    "firstName": "Bob",
    "lastName": "Johnson",
    "fullName": "Bob Johnson",
    "lastSeen": "2023-04-27T12:00:00Z",
    "aboutMe": "Entrepreneur in blockchain technologies.",
    "connectionInterest": "Seeking blockchain experts.",
    "industryInterests": ["Blockchain", "Cryptocurrency"],
    "interestedInBeingACofounder": true,
    "currentSchool": "Harvard",
    "programType": "Business",
    "birthDate": "1990-08-20T00:00:00Z",
    "profilePicture": "https://example.com/path/to/photo.jpg",
    "previousEducation": "Stanford",
    "employmentHistory": "Crypto Startup Founder",
    "hasIdea": "Committed to an idea",
    "technical": true,
    "impressiveAccomplishment": "Launched a successful ICO."
  },
  {
    "userId": "ObjectId('507f1f77bcf86cd799439013')",
    "email": "charlie@example.com",
    "firstName": "Charlie",
    "lastName": "Brown",
    "fullName": "Charlie Brown",
    "lastSeen": "2023-04-27T12:00:00Z",
    "aboutMe": "Aspiring tech innovator.",
    "connectionInterest": "Connecting with future tech leaders.",
    "industryInterests": ["Tech", "Artificial Intelligence"],
    "interestedInBeingACofounder": true,
    "currentSchool": "Stanford",
    "programType": "Engineering",
    "birthDate": "1993-11-11T00:00:00Z",
    "profilePicture": "https://example.com/path/to/photo.jpg",
    "previousEducation": "UC Berkeley",
    "employmentHistory": "Silicon Valley Tech Company",
    "hasIdea": "Don't have an idea yet",
    "technical": true,
    "impressiveAccomplishment": "Developed new software architecture patterns."
  },
  {
    "userId": "ObjectId('507f1f77bcf86cd799439014')",
    "email": "diana@example.com",
    "firstName": "Diana",
    "lastName": "Ross",
    "fullName": "Diana Ross",
    "lastSeen": "2023-04-27T12:00:00Z",
    "aboutMe": "Marketing guru with a passion for startups.",
    "connectionInterest": "Marketing professionals and startup enthusiasts.",
    "industryInterests": ["Marketing and Sales", "Consumer Retail"],
    "interestedInBeingACofounder": false,
    "currentSchool": "Stanford",
    "programType": "Business",
    "birthDate": "1989-07-22T00:00:00Z",
    "profilePicture": "https://example.com/path/to/photo.jpg",
    "previousEducation": "NYU",
    "employmentHistory": "Marketing Director at a tech startup",
    "hasIdea": "Have ideas but not committed",
    "technical": false,
    "impressiveAccomplishment": "Tripled market reach for a new product."
  }
]
